### ISSUE TITLE
res="10_minutes

### ISSUE THREAD

**Issue by ckluss** [brry/rdwd#12]
Hi

thank you for your great package! 

A suggestion for improvement could be to provide the  `res="10_minutes" ` for `selectDWD`. It works but there are no minutes in the `MESS_DATUM` column right now (all set to zero, instead of :00, :10, :20, :30, :40, :50)

```
library(rdwd)
link <- selectDWD("Kiel-Holtenau", res="10_minutes", var="air_temperature", per="recent") 
file <- dataDWD(link, read=FALSE)
air_temperature <- readDWD(file, varnames=TRUE)
air_temperature 
```

Maybe it is line 250 in readDWD.R in addition

`if(nch==12) "%Y%m%d%H%M"  # for 201804270000 `

https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/

Kind regards
Christof

**Comment by brry** [comment]
You're absolutely right. Thanks for pointing it out and providing the solution with it!  
Since I just pushed to CRAN two days ago, the fix will not be on CRAN in the the near future, but the development version is easy to install, see https://github.com/brry/rdwd#latest-version
