### ISSUE TITLE
dataDWD: should dbin default be TRUE?

### ISSUE THREAD

**Issue by brry** [brry/rdwd#20]
Consider the implications of setting the default call to `download.file` with `wb=TRUE`

https://bookdown.org/brry/rdwd/raster-data.html#binary-file-errors

**Comment by adamhsparks** [comment]
Saw this on the R-pkg-devel list.

Yes, you want to do this. Otherwise, it won't properly work on Windows as you've noted. It bit me in https://github.com/ropensci/GSODR as I use macOS or Linux and forgot to set this for binary downloads.
