### ISSUE TITLE
Unzip function for windows

### ISSUE THREAD

**Issue by Mightynasty** [brry/rdwd#23]
Hi, I'm working on windows and when reading file with readDWD I get the following error:

*'unzip' is not recognized as an internal or external command,
operable program or batch file.*

I have both utils and ncdf4 libraries installed, and separately the unzip function works.

**Comment by brry** [comment]
Could you post a reproducible example?

**Comment by Mightynasty** [comment]
Hi ! Here it is:
I used the example similar to the one in the docs:

`link <- selectDWD(id = "150", res="daily", var="kl", per="recent")
file <- dataDWD(link, read=FALSE)
clim <- readDWD(file, varnames=FALSE)`

The console response:

dataDWD -> dirDWD: adding to directory 'C:/Users/Anastasia/Documents/DWDdata'
dataDWD -> newFilename: creating 1 file:
'.../DWDdata/daily_kl_recent_tageswerte_KL_00150_akt.zip'
Reading file with readDWD.data().
'unzip' is not recognized as an internal or external command,
operable program or batch file.
'(unzip -p .../DWDdata/daily_kl_recent_tageswerte_KL_00150_akt.zip produkt_klima_tag_20190221_20200819_00150.txt) > ...\AppData\Local\Temp\RtmpSYVSSB\file43042d986b3c' execution failed with error code 1File '...\AppData\Local\Temp\RtmpSYVSSB\file43042d986b3c' has size 0. Returning a NULL data.frame.File contains no rows: .../DWDdata/daily_kl_recent_tageswerte_KL_00150_akt.zip

**Comment by brry** [comment]
Thanks for the example. It works on my computer. I wonder if this is related to https://github.com/brry/rdwd/issues/22.
Can you try `clim <- readDWD(file, fread=FALSE)`?

**Comment by Mightynasty** [comment]
Perfect, it worked! Now I see it was NA by default.

**Comment by brry** [comment]
Could you try a few things so I can maybe find out where this comes from?
Do you get the same error for the last line here?

 ```r
fp <- unzip(file, list=TRUE) # file produkt*, the actual datafile
fp <- fp$Name[grepl("produkt",fp$Name)]

dat <- data.table::fread(cmd=paste("unzip -p", file, fp), na.strings=berryFunctions::na9(nspace=0),
                                   header=TRUE, sep=";", stringsAsFactors=TRUE, data.table=FALSE)

```
And for the following?
 ```r
dat <- data.table::fread(cmd=paste("unzip -p", file, fp), header=TRUE, sep=";")

```

**Comment by Mightynasty** [comment]
Same error for both: 
```
unzip' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by brry** [comment]
Seems like unzip is only available if you have e.g. a git shell ([source](https://salesforce.stackexchange.com/questions/257846/unzip-is-not-recognized-as-an-internal-or-external-command)). I'll see if I can find an alternative online...

**Comment by Mightynasty** [comment]
Yes, like many commands, only working from the shell. Thanks a lot for you help and work!

**Comment by brry** [comment]
What output do you get with the following?  
`system("unzip", show.output.on.console=FALSE)`

I'm considering keeping the default for fread as NA but not only checking for data.table but also for the unzip command...

**Comment by brry** [comment]
I think I have a solution. Could you run `updateRdwd()` to have version 1.4.1 (2020-08-24) and then run the following two examples?

```r
readDWD(file) # should run fine now
readDWD(file, fread=T) # should give warning [1] and then the error as before
```

Lastly, if you'd want to take the time, could you install [Rtools](https://cran.r-project.org/bin/windows/Rtools) _(directly at C:/Rtools since compiler paths may not have spaces, as there would be with C:/Program Files/R/Rtools/)_ and see if both examples work fine? That would settle issue #22 for me.
Don't feel pressured, though, I don't want to be a burden on your time. I appreciate you pointing out this issue regardless :).

[1] system command 'unzip' could not be found. Expect trouble with data.table::fread.

**Comment by Mightynasty** [comment]
Hi, I tried both, the second one still with the same warning and error. 
Rtools are now directly in C: drive and I restarted everything.
But since the readDWD works it's great! Thank you.

**Comment by brry** [comment]
Thanks so much for checking!
One last question, for clarity: with Rtools installed and R restarted, does it still not work with fread=T? Does it find `Sys.which("unzip")`?

**Comment by Mightynasty** [comment]
The `Sys.which("unzip")` just gives this output: 
`unzip 
   "" `
As for the fread=T, still the same.

**Comment by brry** [comment]
Maybe Rtools was not added to the path. Well, it was worth a try. If you're happy with how it works, so am I.

Thank you so much for trying some things out!

**Comment by brry** [comment]
I just had the same problem on my laptop.
It was easy to solve by adding rtools40 to the PATH. I now have instructions for that online:
https://bookdown.org/brry/rdwd/fread.html
