### ISSUE TITLE
readDwd is creating error in a windows pc  

### ISSUE THREAD

**Issue by NandhiniS08** [brry/rdwd#24]
link <- selectDWD("XXXXXX", res="hourly", var="air_temperature", per="recent")
file <- dataDWD(link, read=FALSE, dir=paste(getwd(),"/data/Weather_Hour/",sep = ""), quiet=TRUE)
clim <- readDWD(file,type = "data" )

Am getting the error
Der Befehl "unzip" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

English version - The command "unzip" is either misspelled or
could not be found. 

i am not able to find a installation of unyip for windows.

**Comment by brry** [comment]
try fread=FALSE in readDWD

**Comment by NandhiniS08** [comment]
Thanks it worked. I thought  the default value is FALSE.

**Comment by brry** [comment]
I set fread to NA in the last cran release. If you get the current development version, it should work with the default, see
https://github.com/brry/rdwd/issues/23
