### ISSUE TITLE
grib2 reading fails

### ISSUE THREAD

**Issue by brry** [brry/rdwd#28]
```r
nwp_t2m_base <- "ftp://opendata.dwd.de/weather/nwp/icon-d2/grib/03/p"
nwp_urls <- indexFTP("", base=nwp_t2m_base, dir=tempdir())
nwp_file <- dataDWD(nwp_urls[6], base=nwp_t2m_base, dir=tempdir(), joinbf=TRUE, dbin=TRUE, read=FALSE)
nwp_data <- readDWD(nwp_file, quiet=TRUE)
```

Fails with messsage from rgdal::readGDAL:
_**.grib2 is a grib file, but no raster dataset was successfully identified._

**Comment by brry** [comment]
Don't know why it worked in [January](https://bookdown.org/brry/rdwd/raster-data.html#readdwd.grib2) - GDAL and icon seem to be incompatible since 2018: https://github.com/OSGeo/gdal/issues/1018

**Comment by brry** [comment]
See also https://www.dwd.de/DE/leistungen/opendata/neuigkeiten/opendata_aug2020_01.html which says
Die Gitterdefinitionsdatei für ICON-D2/ICON-D2-EPS (Deutschland) ist verfügbar unter https://opendata.dwd.de/weather/lib/cdo/ :
    Gitter-Definitionsdatei für ICON-D2/ICON-D2-EPS: https://opendata.dwd.de/weather/lib/cdo/icon_grid_0047_R19B07_L.nc.bz2
    Interpolationsgewichte für ICON-D2/ICON-D2-EPS: https://opendata.dwd.de/weather/lib/cdo/ICON_D2_002_EASY.tar.bz2

**Comment by falk-env** [comment]
Hey Berry,

having [retirement of rgdal, rgeos and maptools](https://r-spatial.org/r/2022/04/12/evolution.html) by the end of 2023 in mind, have you considered migrating to {[stars](https://github.com/r-spatial/stars)}? 

`stars::read_stars("*.grib2")` seems to do the job.

**Comment by brry** [comment]
Hey thanks so much for the pointers! I was not aware of that. It's not perfect as the rdwd maintainer to not follow r-spatial, but time limitations and other real life annoyances get in the way...

I plan to implement stars for grib2 in the next days (before the next CRAN release).

**Comment by falk-env** [comment]
You're very welcome! No worries, maintainance can be quite time-consuming.. 😏

**Comment by brry** [comment]
I added `terra` and `stars` support to `readDWD.grib2()` and noted in the examples which files work and which don't.  
`terra` has a plot function that works out of the box (see the new examples), so I set that as the default `pack`. 

I will close this issue now, but anybody may feel free to reopen it if changes are needed.

**Comment by brry** [comment]
rgdal will be [retired](https://r-spatial.org/r/2022/04/12/evolution.html) 2023, so the rgdal option will be removed. Any contrary wishes can be posted here, of course :)
