### ISSUE TITLE
properly vectorize selectDWD in expansive mode

### ISSUE THREAD

**Issue by NandhiniS08** [brry/rdwd#36]

**Comment by brry** [comment]
Does [this](https://bookdown.org/brry/rdwd/fileindex.html) help?

You should get far with `rdwd::updateRdwd`

**Comment by NandhiniS08** [comment]
Is there a straightfwd way to download air_temperature 10 minute station value for the past 5 years directly?

**Comment by brry** [comment]
Yes, adapt the example from the Readme.
To use the package efficiently, please read the website with some use cases and the individual function documentations

**Comment by brry** [comment]
Note that `selectDWD` ist vectorized and you will have to download the full data sets. Definitely have good folder management to avoid duplicate downloads.

**Comment by NandhiniS08** [comment]
Thanks a lot! that was helpful
Is it also possible to extract all the data from hourly and daily for a given station id?

**Comment by brry** [comment]
Yes, case 2 in the documentation of `selectDWD`:  
2 | \| "xx" | \| "" | \| All file names (across paths) for station id  
For case 2, you can explicitly set res="",var="",per="" to avoid the default interactive selection.

**Comment by NandhiniS08** [comment]
I tried this  selectDWD(id = 5906, res=c("hourly","daily"), per="h",var = ""). But it gives the subdaily and other resolutions as well

**Comment by brry** [comment]
That seems like a bug in selectDWD. Will investigate.

**Comment by brry** [comment]
This one will be somewhat hard to resolve. Properly vectorizing `selectDWD` is on my list, see https://github.com/brry/rdwd/issues/33.  
For now, use this workaround:

```r
library(rdwd)
data("fileIndex")
fileIndex <- fileIndex[fileIndex$id==5906 &
                       fileIndex$res %in% c("hourly","daily") &
                       fileIndex$per=="historical",]
fileIndex <- na.omit(fileIndex)
fileIndex$path # pass this to dataDWD
```

**Comment by brry** [comment]
The `selectDWD `behaviour is now as you expected. Please run `rdwd::updateRdwd()` to get the new version. Please report any problems you might run into :)
