### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [brry/rdwd#38]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by brry** [comment]
I [added a warning](https://github.com/brry/rdwd/commit/d57743d2455ee98a1ce5dcea1ca6fb24b02b3568#diff-5b3dc46791352e1f0c5ad8322ef87bf18e22de5e32c93cef900f8b951c9cc446R1270) if the rgdal option is selected in the one function that uses it. I will remove the dependency early next year, I think.

**Comment by brry** [comment]
The next CRAN release of `rdwd `will no longer suggest `rgdal `:)
