### ISSUE TITLE
Downloads of historic data fails

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [brry/rdwd#42]
First: After many years I finally managed to wrap my head around this DWD data stuff and got something useful (for me) running.
So thank you very much for making these strangely complex datasets available to the (nearly) normal people.

But now that I want to put it in practice, I realize that there seem to be problems downloading historic datasets. This case was not foreseen and now my script got stuck:

```
dataDWD -> dirDWD: adding to directory '/home/bernd/Projekte/R/rdwd'
dataDWD: 1 file already existing and not downloaded again:  'hourly_air_temperature_historical_stundenwerte_TU_05149_20050101_20221004_hist.zip'
Now downloading 3 files...
dataDWD -> newFilename: creating 3 files:
/home/bernd/Projekte/R/rdwd/hourly_air_temperature_historical_stundenwerte_TU_02600_20050301_20221231_hist.zip
/home/bernd/Projekte/R/rdwd/hourly_air_temperature_historical_stundenwerte_TU_05705_19480101_20221231_hist.zip
  (and 1 more)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
Warnmeldung:
3 Downloads have failed (out of 4). Setting read=FALSE. download.file errors:
kann URL 'ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/stundenwerte_TU_02600_20050301_20221231_hist.zip' nicht öffnen
kann URL 'ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/stundenwerte_TU_05705_19480101_20221231_hist.zip' nicht öffnen
kann URL 'ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/stundenwerte_TU_01107_20041201_20221231_hist.zip' nicht öffnen 
```
Actually, the zips are there and can be downloaded manually.
Just ran into this issue late, cause I developed the script with recent data only.

**Comment by Bernd-Vogelgesang** [comment]
Update:
The files names in question do NOT correspond to the URLs. 
It seems, the end date was updated in the zip.name by one year which was hard to realize in the beginning.:

URL ->     stundenwerte_TU_02600_20050301_20221231_hist.zip
ftp ->      stundenwerte_TU_02600_20050301_20231231_hist.zip 

URL ->      stundenwerte_TU_05705_19480101_20221231_hist.zip
ftp ->      stundenwerte_TU_05705_19480101_20231231_hist.zip

URL ->      stundenwerte_TU_01107_20041201_20221231_hist.zip
ftp ->      stundenwerte_TU_01107_20041201_20231231_hist.zip

**Comment by brry** [comment]
Do you already use the github version?

rdwd::updateRdwd()

If yes, I will update the index.

You should have been pointed in a message to
https://bookdown.org/brry/rdwd/fileindex.html

**Comment by Bernd-Vogelgesang** [comment]
arghh, as always: RTFM!
rdwd::updateRdwd() did the trick.

sorry for the noise!

**Comment by brry** [comment]
Little late, but:
no problem at all, glad I could help.

To follow up: with an older version of rdwd (1.8.0 from 2023-06-17), for this code

```r
library(rdwd)
link <- selectDWD(res="hourly", var="air_temperature", per="hist", id=05705)
temp <- dataDWD(link)

```

I get the output

```
dataDWD -> dirDWD: adding to directory '/Users/berry/DWDdata'
dataDWD -> newFilename: creating 1 file:
'/Users/berry/DWDdata/hourly_air_temperature_historical_stundenwerte_TU_05705_19480101_20221231_hist.zip'
Warning message:
1 Download has failed (out of 1). Setting read=FALSE. download.file error:
cannot open URL 'ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/stundenwerte_TU_05705_19480101_20221231_hist.zip'
- If files have been renamed on the DWD server, see   https://bookdown.org/brry/rdwd/fileindex.html 
```

So normally, users should be pointed to the webpage in this case.
