### ISSUE TITLE
the new DWD OpenData server should be used

### ISSUE THREAD

**Issue by ChrisHH** [brry/rdwd#5]
Hi, 

selectDWD loads wrong filenames. 

`link <- selectDWD(res="daily", var="kl", per="rh", outvec = TRUE)`

Due to the following?
[https://www.dwd.de/EN/climate_environment/cdc/cdc_node.html](url)
CDC OpenData
Due to DWD data service restructuring, the CDC-FTP Server is moved to DWD OpenData, allowing access via ftp and https.

The new access is: https://opendata.dwd.de/climate_environment/CDC/ and ftp://opendata.dwd.de/climate_environment/CDC/.

Most data sets, especially the German station data, have been copied already and are now updated synchronously with the FTP-server. For a period of transition, both the new and the old addresses are valid. 

Deadline for termination of address ftp-cdc is: 1st June 2019.

**Comment by brry** [comment]
Thank you so much for seeing this in time! I saw the new access, but didn't realize they're shutting down CDC. I'll be incorporating this in the next days. 

Notes to self: 
- Looks like I only need to change to `dwdbase <- "ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate"
- There's at least one new folder: hourly/wind_synop
- looks like I can use https://opendata.dwd.de/weather/tree.html and ftp://opendata.dwd.de/weather/tree.html for createIndex

**Comment by ChrisHH** [comment]
Thank you! My issue is solved. I had an old version of the package in operation.
After an update, all works fine. Sorry for the confusion.

But good to see, that you have the server change on your list now :-)

Thank you for keeping this nice package up to date!!!
Chris
