### ISSUE TITLE
Access to phenology data ?

### ISSUE THREAD

**Issue by EtienneClaverie** [brry/rdwd#8]
Hi Berry,
With the help of your package you can download data from
ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/climate.
is there a way to download data from :
ftp://opendata.dwd.de/climate_environment/CDC/observations_germany/phenology/
How can I tell rdwd to look into that folder instead ?

Thank you very much,
Best regards,
Etienne

**Comment by brry** [comment]
Real quick on mobile, untested: basically
`dataDWD(base=sub("climate", "phenology", dwdbase), url="some/file", joinbf=TRUE, read=FALSE, dir="DWDdata")`
If you send me a reading function for an example file, I can incorporate that as well.

**Comment by EtienneClaverie** [comment]
Thanks for the quick rresponse! Resolved this issue with 👍 
```
dwdphenology <- paste(sub("climate$", "phenology", dwdbase),"/annual_reporters/crops/historical/",sep="")
dataDWD(base=dwdphenology, file="PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Winterweizen_1925_2018_hist.txt", joinbf=TRUE, read=FALSE, dir="DWDdata")
```
Now next step is to read in the metadata and join the two tables.
Thanks a lot,
Etienne

**Comment by brry** [comment]
Nice. I might add a short example to the use cases vignette. If you have ideas for an example analysis, they'd be welcome ;-)

Note to self: Here's a basic outline for a smaller file:
```r
phenocrop_base <- paste0(sub("climate$", "phenology", dwdbase), 
                        "/annual_reporters/crops/historical/")
# pheno_urls <- indexFTP("", base=phenocrop_base, dir="Pheno")
kohl_url <- "PH_Jahresmelder_Landwirtschaft_Kulturpflanze_Weisskohl_1951_1990_hist.txt"
kohl_file <- dataDWD(base=phenocrop_base, file=kohl_url, joinbf=TRUE, 
                      read=FALSE, dir="Pheno") # 9 MB
kohl <- read.table(kohl_file, sep=";", header=TRUE)

```

**Comment by EtienneClaverie** [comment]
Thanks Berry, this is exactly what I was just writing this morning! Ill make sure I'll send you a short version of my analysis once i am done. I think we can close the case!

**Comment by brry** [comment]
The use case as a direct link: https://bookdown.org/brry/rdwd/use-case-phenology-data.html
