### ISSUE TITLE
newFilename: The following folder does not exist:  ''

### ISSUE THREAD

**Issue by yannikbuhl** [brry/rdwd#9]
Dear brry,

first, thanks so much for the handy package! I started using it today and encountered an error whose origins I could not determine. The following is my code:

`download <- selectDWD(id = stations, res = "daily", outvec = TRUE)`
`res1 <- dataDWD(file = download, dir = "Y:/This/Is/My/Path/dataDWD")`

R keeps telling me:
`dataDWD -> dirDWD: adding to directory 'Y:/This/Is/My/Path/dataDWD'`
`Error: dataDWD -> newFilename: The following folder does not exist:  ''`

This happens even when I use:
`res1 <- dataDWD(file = download)`

Then, it creates the folder correctly at the current `getwd()` location, but kinda refuses to fill it.

Do you know any help?

**Comment by brry** [comment]
Hm, that's a tough one. `dirname('Y:/This/Is/My/Path')` seems to return an empty string. Can you verify that?
What do you get with a parent directory existence check, i.e. `dir.exists('Y:/This/Is/My/Path')`

As to the second one: is your `getwd()` writable (write permission)? What do you mean with "kinda refuses to fill it"?

**Comment by yannikbuhl** [comment]
It's a work computer, I tried my private laptop and it works here. Usually, I have writing access on my work computer's path, even through R/RStudio (if I use `download.file` for example). I'll try to figure it out more in detail on Monday.
